CREATE DATABASE QuanLyBanHang;
ALTER DATABASE QuanLyBanHang CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE QuanLyBanHang;

CREATE TABLE CUSTOMER(
    cID INT NOT NULL PRIMARY KEY,
    cName VARCHAR(100) NOT NULL,
    cAge INT NULL
);

CREATE TABLE ORDER1(
    oID INT NOT NULL,
    cID INT NOT NULL,
    oDate DATETIME NOT NULL,
    oTotalPrice FLOAT NOT NULL,
    PRIMARY KEY (oID),
    FOREIGN KEY (cID) REFERENCES CUSTOMER(cID)
);

CREATE TABLE PRODUCT(
    pID INT NOT NULL PRIMARY KEY,
    pName VARCHAR(100) NOT NULL,
    pPrice FLOAT NOT NULL
);

CREATE TABLE ORDERDETAIL(
    oID INT NOT NULL,
    pID INT NOT NULL,
    odQTy INT NOT NULL,    
    PRIMARY KEY (oID, cID),
    FOREIGN KEY (oID) REFERENCES ORDER1(oID),
    FOREIGN KEY (pID) REFERENCES PRODUCT(pID)
);
